# Welcome to Jekyll!

title: Aspire Workshop 
email: rick.neeft@outlook.com
description: "Aspire workshop course site"
baseurl: "/aspire-workshop" # the subpath of your site, e.g. /blog
url: "https://www.rickneeft.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  rneeft

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

color_scheme: 
  light

mermaid:
  version: "11.6.0"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
